/* ============================================================
   data.js — catalogue local de films & séries
   Aucune clé API, aucun compte : les données sont embarquées
   directement dans le projet. Remplace les appels réseau à TMDB.
   ============================================================ */

const LOCAL_CATALOGUE = [
  // ---------------- FILMS ----------------
  { id: 1, type: "movie", titre: "Inception", date: "2010-01-01", note: 8.4,
    genres: ["Science-Fiction", "Thriller"], duree: 148,
    overview: "Un voleur capable de s'infiltrer dans les rêves des autres se voit confier une mission inverse : implanter une idée plutôt que la dérober.",
    cast: [{name:"Leonardo DiCaprio", character:"Dom Cobb"},{name:"Joseph Gordon-Levitt", character:"Arthur"},{name:"Elliot Page", character:"Ariadne"},{name:"Tom Hardy", character:"Eames"}] },
  { id: 2, type: "movie", titre: "The Matrix", date: "1999-01-01", note: 8.2,
    genres: ["Science-Fiction", "Action"], duree: 136,
    overview: "Un programmeur découvre que le monde qu'il connaît est une simulation informatique et rejoint la résistance humaine.",
    cast: [{name:"Keanu Reeves", character:"Neo"},{name:"Laurence Fishburne", character:"Morpheus"},{name:"Carrie-Anne Moss", character:"Trinity"}] },
  { id: 3, type: "movie", titre: "Parasite", date: "2019-01-01", note: 8.5,
    genres: ["Drame", "Thriller"], duree: 132,
    overview: "Une famille modeste s'infiltre peu à peu dans le foyer d'une famille aisée, jusqu'à ce que les apparences se fissurent.",
    cast: [{name:"Song Kang-ho", character:"Kim Ki-taek"},{name:"Lee Sun-kyun", character:"Park Dong-ik"},{name:"Cho Yeo-jeong", character:"Park Yeon-kyo"}] },
  { id: 4, type: "movie", titre: "The Grand Budapest Hotel", date: "2014-01-01", note: 8.1,
    genres: ["Comédie", "Drame"], duree: 99,
    overview: "Les aventures d'un concierge légendaire et de son jeune protégé dans un hôtel européen entre deux guerres.",
    cast: [{name:"Ralph Fiennes", character:"Gustave H."},{name:"Tony Revolori", character:"Zero"}] },
  { id: 5, type: "movie", titre: "Le Voyage de Chihiro", date: "2001-01-01", note: 8.6,
    genres: ["Animation", "Fantastique"], duree: 125,
    overview: "Une fillette se retrouve piégée dans un monde peuplé d'esprits et doit retrouver ses parents transformés en cochons.",
    cast: [{name:"Rumi Hiiragi", character:"Chihiro"},{name:"Miyu Irino", character:"Haku"}] },
  { id: 6, type: "movie", titre: "Mad Max: Fury Road", date: "2015-01-01", note: 8.1,
    genres: ["Action", "Aventure"], duree: 120,
    overview: "Dans un désert post-apocalyptique, une fugitive et un survivant s'allient pour fuir un tyran et ses hordes motorisées.",
    cast: [{name:"Tom Hardy", character:"Max"},{name:"Charlize Theron", character:"Furiosa"}] },
  { id: 7, type: "movie", titre: "The Dark Knight", date: "2008-01-01", note: 9.0,
    genres: ["Action", "Crime", "Drame"], duree: 152,
    overview: "Batman affronte le Joker, un criminel chaotique qui plonge Gotham dans le chaos pour éprouver ses principes.",
    cast: [{name:"Christian Bale", character:"Bruce Wayne"},{name:"Heath Ledger", character:"Le Joker"},{name:"Aaron Eckhart", character:"Harvey Dent"}] },
  { id: 8, type: "movie", titre: "Pulp Fiction", date: "1994-01-01", note: 8.9,
    genres: ["Crime", "Drame"], duree: 154,
    overview: "Les destins entremêlés de deux tueurs à gages, d'un boxeur et d'un couple de braqueurs à Los Angeles.",
    cast: [{name:"John Travolta", character:"Vincent Vega"},{name:"Samuel L. Jackson", character:"Jules Winnfield"},{name:"Uma Thurman", character:"Mia Wallace"}] },
  { id: 9, type: "movie", titre: "La La Land", date: "2016-01-01", note: 8.0,
    genres: ["Comédie musicale", "Romance"], duree: 128,
    overview: "Une actrice en devenir et un pianiste de jazz voient leur histoire d'amour se heurter à leurs ambitions respectives.",
    cast: [{name:"Ryan Gosling", character:"Sebastian"},{name:"Emma Stone", character:"Mia"}] },
  { id: 10, type: "movie", titre: "Get Out", date: "2017-01-01", note: 7.7,
    genres: ["Horreur", "Thriller"], duree: 104,
    overview: "Un jeune homme rend visite à la famille de sa petite amie et découvre que leur hospitalité cache un terrible secret.",
    cast: [{name:"Daniel Kaluuya", character:"Chris Washington"},{name:"Allison Williams", character:"Rose"}] },
  { id: 11, type: "movie", titre: "Premier Contact", date: "2016-01-01", note: 7.9,
    genres: ["Science-Fiction", "Drame"], duree: 116,
    overview: "Une linguiste est recrutée par l'armée pour établir le dialogue avec des vaisseaux extraterrestres apparus sur Terre.",
    cast: [{name:"Amy Adams", character:"Louise Banks"},{name:"Jeremy Renner", character:"Ian Donnelly"}] },
  { id: 12, type: "movie", titre: "Whiplash", date: "2014-01-01", note: 8.5,
    genres: ["Drame", "Musique"], duree: 106,
    overview: "Un jeune batteur ambitieux se soumet aux méthodes brutales d'un professeur de conservatoire obsédé par l'excellence.",
    cast: [{name:"Miles Teller", character:"Andrew Neiman"},{name:"J.K. Simmons", character:"Terence Fletcher"}] },
  { id: 13, type: "movie", titre: "Les Évadés", date: "1994-01-01", note: 9.3,
    genres: ["Drame"], duree: 142,
    overview: "Condamné à tort, un banquier tisse patiemment un plan d'évasion et d'amitié au sein d'une prison impitoyable.",
    cast: [{name:"Tim Robbins", character:"Andy Dufresne"},{name:"Morgan Freeman", character:"Red"}] },
  { id: 14, type: "movie", titre: "Coco", date: "2017-01-01", note: 8.4,
    genres: ["Animation", "Familial"], duree: 105,
    overview: "Un jeune garçon passionné de musique se retrouve transporté au Pays des Morts et part à la recherche de ses ancêtres.",
    cast: [{name:"Anthony Gonzalez", character:"Miguel"},{name:"Gael García Bernal", character:"Héctor"}] },
  { id: 15, type: "movie", titre: "À Couteaux Tirés", date: "2019-01-01", note: 7.9,
    genres: ["Comédie", "Mystère", "Crime"], duree: 130,
    overview: "À la mort d'un riche écrivain, un détective haut en couleur enquête au sein d'une famille où chacun a un mobile.",
    cast: [{name:"Daniel Craig", character:"Benoit Blanc"},{name:"Ana de Armas", character:"Marta Cabrera"}] },
  { id: 16, type: "movie", titre: "Dune", date: "2021-01-01", note: 8.0,
    genres: ["Science-Fiction", "Aventure"], duree: 155,
    overview: "L'héritier d'une grande maison noble part sur la planète désertique Arrakis, enjeu d'une lutte de pouvoir interstellaire.",
    cast: [{name:"Timothée Chalamet", character:"Paul Atreides"},{name:"Zendaya", character:"Chani"},{name:"Rebecca Ferguson", character:"Lady Jessica"}] },
  { id: 17, type: "movie", titre: "Everything Everywhere All at Once", date: "2022-01-01", note: 7.8,
    genres: ["Science-Fiction", "Comédie", "Action"], duree: 140,
    overview: "Une commerçante débordée découvre qu'elle peut accéder aux vies qu'elle aurait pu mener dans des univers parallèles.",
    cast: [{name:"Michelle Yeoh", character:"Evelyn"},{name:"Ke Huy Quan", character:"Waymond"},{name:"Jamie Lee Curtis", character:"Deirdre"}] },
  { id: 18, type: "movie", titre: "The Social Network", date: "2010-01-01", note: 7.7,
    genres: ["Drame", "Biographie"], duree: 120,
    overview: "La création controversée de Facebook et les batailles judiciaires qui ont opposé ses fondateurs.",
    cast: [{name:"Jesse Eisenberg", character:"Mark Zuckerberg"},{name:"Andrew Garfield", character:"Eduardo Saverin"}] },
  { id: 19, type: "movie", titre: "Interstellar", date: "2014-01-01", note: 8.7,
    genres: ["Science-Fiction", "Drame"], duree: 169,
    overview: "Alors que la Terre devient inhabitable, un groupe d'explorateurs franchit un trou de ver à la recherche d'un nouveau foyer pour l'humanité.",
    cast: [{name:"Matthew McConaughey", character:"Cooper"},{name:"Anne Hathaway", character:"Brand"},{name:"Jessica Chastain", character:"Murph"}] },
  { id: 20, type: "movie", titre: "Amélie Poulain", date: "2001-01-01", note: 8.3,
    genres: ["Comédie", "Romance"], duree: 122,
    overview: "Une jeune serveuse parisienne, rêveuse et espiègle, se met en tête d'améliorer discrètement la vie de son entourage.",
    cast: [{name:"Audrey Tautou", character:"Amélie"},{name:"Mathieu Kassovitz", character:"Nino"}] },
  { id: 21, type: "movie", titre: "Portrait de la Jeune Fille en Feu", date: "2019-01-01", note: 8.1,
    genres: ["Drame", "Romance"], duree: 122,
    overview: "Sur une île bretonne du XVIIIe siècle, une peintre doit réaliser en secret le portrait de fiançailles d'une jeune femme rebelle.",
    cast: [{name:"Noémie Merlant", character:"Marianne"},{name:"Adèle Haenel", character:"Héloïse"}] },
  { id: 22, type: "movie", titre: "Joker", date: "2019-01-01", note: 8.4,
    genres: ["Drame", "Crime", "Thriller"], duree: 122,
    overview: "Un comédien raté et rejeté par la société de Gotham bascule peu à peu dans la folie et la violence.",
    cast: [{name:"Joaquin Phoenix", character:"Arthur Fleck"},{name:"Robert De Niro", character:"Murray Franklin"}] },

  // ---------------- SÉRIES ----------------
  { id: 101, type: "tv", titre: "Breaking Bad", date: "2008-01-01", note: 9.5,
    genres: ["Crime", "Drame", "Thriller"], saisons: 5,
    overview: "Un professeur de chimie atteint d'un cancer se lance dans la fabrication de méthamphétamine pour assurer l'avenir financier de sa famille.",
    cast: [{name:"Bryan Cranston", character:"Walter White"},{name:"Aaron Paul", character:"Jesse Pinkman"},{name:"Anna Gunn", character:"Skyler White"}] },
  { id: 102, type: "tv", titre: "Stranger Things", date: "2016-01-01", note: 8.6,
    genres: ["Fantastique", "Horreur", "Science-Fiction"], saisons: 4,
    overview: "Dans une petite ville des années 80, la disparition d'un enfant révèle des expériences secrètes et une dimension parallèle terrifiante.",
    cast: [{name:"Millie Bobby Brown", character:"Eleven"},{name:"Finn Wolfhard", character:"Mike"},{name:"Winona Ryder", character:"Joyce Byers"}] },
  { id: 103, type: "tv", titre: "The Office (US)", date: "2005-01-01", note: 8.9,
    genres: ["Comédie"], saisons: 9,
    overview: "Le quotidien absurde et attachant des employés d'une entreprise de papier filmé sous forme de faux documentaire.",
    cast: [{name:"Steve Carell", character:"Michael Scott"},{name:"John Krasinski", character:"Jim Halpert"},{name:"Jenna Fischer", character:"Pam Beesly"}] },
  { id: 104, type: "tv", titre: "Game of Thrones", date: "2011-01-01", note: 9.2,
    genres: ["Fantastique", "Drame", "Aventure"], saisons: 8,
    overview: "Plusieurs familles nobles se disputent le Trône de Fer tandis qu'une menace ancienne se réveille au-delà du Mur.",
    cast: [{name:"Emilia Clarke", character:"Daenerys Targaryen"},{name:"Kit Harington", character:"Jon Snow"},{name:"Peter Dinklage", character:"Tyrion Lannister"}] },
  { id: 105, type: "tv", titre: "The Crown", date: "2016-01-01", note: 8.6,
    genres: ["Drame", "Histoire"], saisons: 6,
    overview: "La vie de la reine Elizabeth II et de la famille royale britannique, des années 1940 jusqu'à l'époque moderne.",
    cast: [{name:"Claire Foy", character:"Elizabeth II"},{name:"Olivia Colman", character:"Elizabeth II"},{name:"Matt Smith", character:"Prince Philip"}] },
  { id: 106, type: "tv", titre: "Sherlock", date: "2010-01-01", note: 9.1,
    genres: ["Crime", "Drame", "Mystère"], saisons: 4,
    overview: "Le célèbre détective consultant et son fidèle acolyte résolvent des enquêtes dans un Londres contemporain.",
    cast: [{name:"Benedict Cumberbatch", character:"Sherlock Holmes"},{name:"Martin Freeman", character:"John Watson"}] },
  { id: 107, type: "tv", titre: "Fleabag", date: "2016-01-01", note: 8.7,
    genres: ["Comédie", "Drame"], saisons: 2,
    overview: "Une jeune femme londonienne, cynique et en deuil, navigue entre chagrin, désir et autodestruction avec un humour féroce.",
    cast: [{name:"Phoebe Waller-Bridge", character:"Fleabag"},{name:"Sian Clifford", character:"Claire"}] },
  { id: 108, type: "tv", titre: "Chernobyl", date: "2019-01-01", note: 9.3,
    genres: ["Drame", "Histoire", "Thriller"], saisons: 1,
    overview: "La catastrophe nucléaire de Tchernobyl en 1986 et les efforts, héroïques et tragiques, pour en limiter les conséquences.",
    cast: [{name:"Jared Harris", character:"Valery Legasov"},{name:"Stellan Skarsgård", character:"Boris Chtcherbina"}] },
  { id: 109, type: "tv", titre: "The Mandalorian", date: "2019-01-01", note: 8.7,
    genres: ["Science-Fiction", "Aventure", "Action"], saisons: 3,
    overview: "Aux confins de la galaxie, un chasseur de primes solitaire prend sous sa protection un mystérieux et jeune enfant.",
    cast: [{name:"Pedro Pascal", character:"Din Djarin"},{name:"Carl Weathers", character:"Greef Karga"}] },
  { id: 110, type: "tv", titre: "La Casa de Papel", date: "2017-01-01", note: 8.2,
    genres: ["Crime", "Thriller", "Drame"], saisons: 5,
    overview: "Un groupe de braqueurs orchestré par un stratège mystérieux s'attaque à la Fabrique Nationale de la Monnaie espagnole.",
    cast: [{name:"Úrsula Corberó", character:"Tokyo"},{name:"Álvaro Morte", character:"Le Professeur"}] },
  { id: 111, type: "tv", titre: "Dark", date: "2017-01-01", note: 8.7,
    genres: ["Science-Fiction", "Mystère", "Thriller"], saisons: 3,
    overview: "La disparition d'enfants dans une petite ville allemande révèle des connexions vertigineuses entre quatre familles à travers le temps.",
    cast: [{name:"Louis Hofmann", character:"Jonas Kahnwald"},{name:"Lisa Vicari", character:"Martha Nielsen"}] },
  { id: 112, type: "tv", titre: "Brooklyn Nine-Nine", date: "2013-01-01", note: 8.4,
    genres: ["Comédie", "Crime"], saisons: 8,
    overview: "Le quotidien loufoque d'un commissariat de Brooklyn mené par un capitaine pointilleux et une équipe de flics indisciplinés.",
    cast: [{name:"Andy Samberg", character:"Jake Peralta"},{name:"Andre Braugher", character:"Raymond Holt"}] },
  { id: 113, type: "tv", titre: "The Witcher", date: "2019-01-01", note: 8.0,
    genres: ["Fantastique", "Aventure", "Action"], saisons: 3,
    overview: "Un chasseur de monstres mutant tente de trouver sa place dans un monde où les humains sont souvent plus monstrueux que les créatures.",
    cast: [{name:"Henry Cavill", character:"Geralt de Riv"},{name:"Freya Allan", character:"Ciri"}] },
  { id: 114, type: "tv", titre: "Succession", date: "2018-01-01", note: 8.8,
    genres: ["Drame"], saisons: 4,
    overview: "La lutte de pouvoir sans merci entre les enfants d'un magnat vieillissant des médias pour la succession de son empire.",
    cast: [{name:"Brian Cox", character:"Logan Roy"},{name:"Jeremy Strong", character:"Kendall Roy"},{name:"Sarah Snook", character:"Shiv Roy"}] },
  { id: 115, type: "tv", titre: "Peaky Blinders", date: "2013-01-01", note: 8.8,
    genres: ["Crime", "Drame"], saisons: 6,
    overview: "Dans le Birmingham de l'après-guerre, un gang familial mené par un chef charismatique étend son influence par la violence et la ruse.",
    cast: [{name:"Cillian Murphy", character:"Thomas Shelby"},{name:"Helen McCrory", character:"Polly Gray"}] },
  { id: 116, type: "tv", titre: "Black Mirror", date: "2011-01-01", note: 8.7,
    genres: ["Science-Fiction", "Drame", "Thriller"], saisons: 6,
    overview: "Une anthologie d'histoires indépendantes qui explorent les dérives technologiques et leurs effets troublants sur la société.",
    cast: [{name:"Divers acteurs (anthologie)", character:""}] },
  { id: 117, type: "tv", titre: "Ted Lasso", date: "2020-01-01", note: 8.8,
    genres: ["Comédie", "Drame", "Sport"], saisons: 3,
    overview: "Un entraîneur de football américain sans expérience du ballon rond débarque à la tête d'un club anglais en difficulté.",
    cast: [{name:"Jason Sudeikis", character:"Ted Lasso"},{name:"Hannah Waddingham", character:"Rebecca Welton"}] },
  { id: 118, type: "tv", titre: "Better Call Saul", date: "2015-01-01", note: 8.9,
    genres: ["Crime", "Drame"], saisons: 6,
    overview: "Les années de formation d'un avocat opportuniste, avant qu'il ne devienne le sulfureux Saul Goodman.",
    cast: [{name:"Bob Odenkirk", character:"Jimmy McGill"},{name:"Rhea Seehorn", character:"Kim Wexler"}] },
  { id: 119, type: "tv", titre: "The Bear", date: "2022-01-01", note: 8.6,
    genres: ["Comédie", "Drame"], saisons: 3,
    overview: "Un jeune chef étoilé revient dans sa ville natale pour reprendre le sandwicherie familiale en plein chaos.",
    cast: [{name:"Jeremy Allen White", character:"Carmy"},{name:"Ayo Edebiri", character:"Sydney"}] },
  { id: 120, type: "tv", titre: "House of the Dragon", date: "2022-01-01", note: 8.4,
    genres: ["Fantastique", "Drame", "Aventure"], saisons: 2,
    overview: "Deux cents ans avant les événements de Game of Thrones, la maison Targaryen sombre dans une guerre civile pour le trône.",
    cast: [{name:"Matt Smith", character:"Daemon Targaryen"},{name:"Emma D'Arcy", character:"Rhaenyra Targaryen"}] },
  { id: 121, type: "tv", titre: "Arcane", date: "2021-01-01", note: 9.0,
    genres: ["Animation", "Fantastique", "Action"], saisons: 2,
    overview: "Deux sœurs se retrouvent de part et d'autre d'un conflit grandissant entre les cités jumelles de Piltover et Zaun.",
    cast: [{name:"Hailee Steinfeld", character:"Vi"},{name:"Ella Purnell", character:"Jinx"}] }
];
